export const categories = [
    "GENERIC",
    "STUDENT PILOT ENDORSEMENTS",
    "ADDITIONAL STUDENT PILOT ENDORSEMENTS FOR STUDENTS SEEKING SPORT OR RECREATIONAL PILOT CERTIFICATES",
    "SPORT PILOT ENDORSEMENTS",
    "RECREATIONAL PILOT ENDORSEMENTS",
    "PRIVATE PILOT ENDORSEMENTS",
    "COMMERCIAL PILOT ENDORSEMENTS",
    "AIRLINE TRANSPORT PILOT (ATP) ENDORSEMENTS",
    "INSTRUMENT RATING ENDORSEMENTS",
    "FLIGHT INSTRUCTOR (OTHER THAN FLIGHT INSTRUCTORS WITH A SPORT PILOT RATING) ENDORSEMENTS",
    "FLIGHT INSTRUCTOR WITH A SPORT PILOT RATING ENDORSEMENT",
    "GROUND INSTRUCTOR ENDORSEMENT",
    "SPECIAL FEDERAL AVIATION REGULATION (SFAR) 73, ROBINSON R-22/R-44 SPECIAL TRAINING AND EXPERIENCE REQUIREMENTS, ENDORSEMENTS",
    "ADDITIONAL ENDORSEMENTS",
    "NIGHT VISION GOGGLES (NVG) OPERATIONS",
    "ENHANCED FLIGHT VISION SYSTEM (EFVS)"
]

export const generic_endorsements = [
    {name: "Prerequisites for practical test", id: "A1"},
    {name: "Review of deficiencies identified on airman knowledge test", id: "A2"}
]